Kafka producer consumer setup
ripe-tech/ripe-bus-api-js pull request #1
Opened 2020-09-21 15:04 UTC by BeeMargarida

| - | - |
| --- | --- |
| Issue | Related to https://github.com/ripe-tech/ripe-registry/issues/30 |
| Decisions | Initial setup for the repo, with API for kafka producer and consumer. The setup of the Kafka client and respective producer and consumer is made using `yonius.json`, and a consumer and producer is created. The consumer subscribes to the given topics, and the producer produces to the topic given when the produce request is made. <br><br> **Consumer**: <br> • The client needs to pass 3 functions: `messageProcessor` responsible for processing each message received in the bus, `sendConfirmation` that is called if the processing is successful and `sendError`, if the processing is not successful. <br> • The consumer is responsible for the retry logic, and will try the given number of retries until they expire. When that happens, the `sendError` message is called. <br><br> **Producer**: <br> • Sends an array of messages given, which will be converted to strings if they are provided as objects.  |
| Animated GIF | -- |

2020-09-21 17:11 UTC, joamag requested changes

2020-09-21 17:11 UTC, joamag commented on js/consumer.js
> +console.log(fs);
?

2020-09-21 17:11 UTC, joamag commented on js/consumer.js
> +export class Consumer {
Let's use the adapter pattern KafkaConsumer that respects the base consumer API

2020-09-21 17:11 UTC, joamag commented on js/producer.js
> +export class Producer {
Same here Kakka producer that respects a common producer API

2020-09-21 17:14 UTC, joamag commented
@BeeMargarida on top of these changes an upper layer for producing events should exist where the inner details are abstract (connection, etc.) so that a consumer node could just do something like

```javascript
bus.trigger("order.create", {order_number: "32132", ...})
```

all the singleton client-related logic is abstract by this API and the first time a trigger occurs a connection is established via the currently active engine and using the configuration details

2020-09-21 17:19 UTC, joamag commented
For the upper layer consumer API the equivalent: 

```javascript
bus.bind("order.created", (order) => {
});
```

2020-09-22 10:55 UTC, BeeMargarida commented
@joamag I implemented a default `onSuccess` and `onError` logic, which can be overwritten by the options object in the `bind` and `trigger` methods. Regarding errors in the callback of bind, I changed the implementation to a try catch.

I have a doubt however, regarding the parameters for the Kafka client, consumer and producer. For now they are using the values in the `yonius.json`, but would it be better to allow them to be overridden by a `kwargs` in the API constructor?

2020-09-22 13:59 UTC, joamag requested changes

2020-09-22 13:59 UTC, joamag commented on README.md
> +bus.bind("order", (message) => { ... })
separate bind from trigger and make the second parameter either a function or an Object

2020-09-22 13:59 UTC, joamag commented on js/kafkaClient.js
> +    var client = null;
var ?

2020-09-22 13:59 UTC, joamag commented on js/kafkaConsumer.js
> +        const data = fs.readFileSync(`${dir}/retry.json`, { encoding: "utf-8" });
use the async fs api

2020-09-22 13:59 UTC, joamag commented on js/kafkaConsumer.js
> +        const data = fs.readFileSync(`${dir}/retry.json`, { encoding: "utf-8" });
https://nodejs.org/api/fs.html#fs_fs_promises_api

2020-09-22 13:59 UTC, joamag commented on js/kafkaConsumer.js
> +        if (this.retryBuffer.length === 0) return;
encapsulate this around a `KafkaRetryConsumer` abstraction that inherits from `KafkaConsumer`

2020-09-22 13:59 UTC, joamag commented on js/kafkaProducer.js
> +            acks: conf("KAFKA_PRODUCER_ACKS", 0),
try to make this as part of the constructor logic

2020-09-22 13:59 UTC, joamag commented on js/kafkaProducer.js
> +        const kafkaClient = KafkaClient.getInstance();
`options.acks === undefined ? conf("KAFKA_PRODUCER_ACKS", trure) : options.acks`

2020-09-22 13:59 UTC, joamag commented on js/kafkaProducer.js
> +            acks: conf("KAFKA_PRODUCER_ACKS", 0),
`acks: options.acks === undefined ? this.acks : options.acks`

2020-09-23 14:48 UTC, joamag approved these changes

2020-09-23 14:48 UTC, merged

2020-09-23 14:54 UTC, joamag commented
👍