Kafka topic name sanitizer
ripe-tech/ripe-bus-api-js pull request #15
Opened 2021-02-10 16:14 UTC by joao-conde

| - | - |
| --- | --- |
| Issue | -- |
| Dependencies | -- |
| Decisions | Adapt on the in/out the kafka topic name. Kafka topics have name [restrictions](https://github.com/apache/kafka/blob/0.10.2/core/src/main/scala/kafka/common/Topic.scala#L29). We already use the adapter pattern so this change does not structurally change anything. |

2021-02-10 16:32 UTC, gcandal requested changes

2021-02-10 16:32 UTC, gcandal commented on js/kafka/kafka-consumer.js
> -
Revert, keep the newline.

2021-02-10 16:32 UTC, gcandal commented on js/kafka/utils.js
> +export const sanitizeTopicName = topic => {
Move to the existing file (https://github.com/ripe-tech/ripe-bus-api-js/blob/master/js/kafka/kafka-client.js), use the same way to declare a function (using `function()...` and add jsdocs.

2021-02-11 06:30 UTC, joamag commented
@joao-conde please re-check that everything is still working, another major design change happened

2021-02-11 06:31 UTC, joamag commented
Adding fast-track to try to merge this ASAP

2021-02-11 09:48 UTC, joao-conde commented
Everything worked and passed the following manual tests:

```js
// bind with event filtering
const callback = message => console.log(message);
(async () => {
    try {
        await bus.bind("topic", { 
            events: ["topic.created", "topic.sent", "topic.tobias"],
            callback: callback,
        })
    } catch (e) {}
})();

// trigger with unsanitized topic name
(async () => {
    try {
        await bus.trigger("ripe_twitch:order.created", "Unsanitized topic name");
    } catch (e) {}
})();

// trigger with metadata override
(async () => {
    try {
        await bus.trigger("topic.created", "topic.created", {
            origin: "overriden",
            hostname: "overriden",
            datatype: "json",
            timestamp: 10000
        });
    } catch (e) {}
})();

// trigger with topic override
(async () => {
    try {
        await bus.trigger("another.created", "Hello World", {
            topic: "topic"
        });
    } catch (e) {}
})();
```

2021-02-11 11:44 UTC, joamag approved these changes

2021-02-11 11:45 UTC, merged

2021-02-11 11:45 UTC, joamag commented
Releasing new version now!

2021-02-11 11:46 UTC, joamag commented
0.3.0