List topics
ripe-tech/ripe-bus-api-js pull request #16
Opened 2021-02-11 15:21 UTC by joao-conde

| - | - |
| --- | --- |
| Issue | -- |
| Dependencies | -- |
| Decisions | 1. `listTopics` method on the client interface (not consumer nor producer specific)<br>2. base implements the `listTopics` as finding out the client adapter and getting an instance; for that reason I have created a kafka-retry-client that just extends the kafka-client (similarly to the kafka-producer and kafka-retry-producer relation).<br>3. I transformed our client instance into an admin instance (alternatively could be invoked whenever needed, a.k.a when the call to topics() is made. <br>4. Kafka adapter list topics is simply calling KafkaJS client `listTopics`|

2021-02-11 15:42 UTC, gcandal requested changes
I believe that because of our questionable dual consumer/producer design this needs a slightly different approach:
- `async listTopics` in `API`: uses either the producer or consumer, depending on what exists. If none does, ensures a producer and uses it. This producer/consumer retrieval should be its own method.
- `async listTopics` in `Producer` and `Consumer`: unimplemented
- `KafkaConsumer` and `KafkaProducer` implement `async listTopics` the same way

2021-02-11 15:42 UTC, gcandal commented on js/kafka/kafka-client.js
> +    get topics() {
This can't be `get` because it's `async`

2021-02-11 15:42 UTC, gcandal commented on js/kafka/kafka-client.js
> +        }).admin();
Do this only when using methods that require it

2021-02-11 15:48 UTC, joao-conde commented
> 
> 
> I believe that because of our questionable dual consumer/producer design this needs a slightly different approach:
> 
>     * `async listTopics` in `API`: uses either the producer or consumer, depending on what exists. If none does, ensures a producer and uses it. This producer/consumer retrieval should be its own method.
> 
>     * `async listTopics` in `Producer` and `Consumer`: unimplemented
> 
>     * `KafkaConsumer` and `KafkaProducer` implement `async listTopics` the same way

But are we not:

a) duplicating the fetching topics code (in kafka producer and consumer)
b) conceptually making a mistake, since the available topics are for a given client connection and not to a specific producer/consumer

2021-02-11 16:30 UTC, gcandal commented
a) Yes, but:
 - It's one line
 - They don't share an ancestor where you can place the functionality
 - Your solution exposes `Client` as an adapter, which is not true. Until now the `API` never accessed it
b) No, because:
 - "connection" doesn't exist as a high-level concept that the lib clients are exposed to
 - They share the same connection anyway

2021-02-11 18:12 UTC, gcandal requested changes
Add the Typescript definition.

2021-02-11 18:12 UTC, gcandal commented on js/base.js
> +     * @returns {String[]} The topic names.
In vanilla javascript we don't go so far with the typing
```suggestion
     * @returns {Array} The topic names.
```

2021-02-11 18:12 UTC, gcandal commented on js/base.js
> +     * @param {Function|Object} options Object that includes configuration variables.
Unless optionals are essential for what you need to do let's avoid them, as it brings extra complexity. It's not only an extra argument, it's writing the types for it and making sure the options aren't kafka-specific.

2021-02-11 19:17 UTC, joamag approved these changes

2021-02-11 19:17 UTC, joamag commented
@joao-conde changed method naming

2021-02-11 19:17 UTC, merged

2021-02-11 22:57 UTC, gcandal commented
> @joao-conde changed method naming

@joamag we had gotten the naming from https://github.com/ripe-tech/ripe-twitch-api-js/blob/f7d17c894b5b9e1dccad80aca7dd5ea1f3277366/js/order.js#L15

This is not exactly LCRUD so it's not the same case though.

2021-02-12 08:58 UTC, joamag commented
> > @joao-conde changed method naming
> 
> @joamag we had gotten the naming from https://github.com/ripe-tech/ripe-twitch-api-js/blob/f7d17c894b5b9e1dccad80aca7dd5ea1f3277366/js/order.js#L15
> 
> This is not exactly LCRUD so it's not the same case though.

Yeah it seemed simple to call it just topics